name: Lint, Test & Deploy on push
on: push 
jobs:
  lint: 
    runs-on: ubuntu-22.04
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/nodejs@v3 
      - name: install dependencies
        run: npm ci 
      - name: run lint 
        run: npm lint 
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/nodejs@v3 
      - name: install dependencies
        run: npm ci 
      - name: run test
        run: npm test
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/nodejs@v3 
      - name: install dependencies
        run: npm ci 
      - name: run deploy
        run: echo "deploying ..."
